nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com/playht":
    npmAuthToken: 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

npmScopes:
  playht:
    npmRegistryServer: "https://npm.pkg.github.com/playht"

yarnPath: .yarn/releases/yarn-3.6.2.cjs
